function(GameCat_R3_MPLAB_assemble_rule target)
    set(inputVar "-mcpu=24HJ128GP504;-g;-DXPRJ_MPLAB=MPLAB;-Wa,--defsym=__MPLAB_BUILD=1,--no-relax,;-mdfp=/home/xDNA/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_DRIVERS_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_CONTROL_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_HARD;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_SOFT;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_MAIN;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_INTERRUPTIONS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_STREAMS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_TASK;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Include;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/PIC24;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/MemMang")
endfunction()
function(GameCat_R3_MPLAB_assemblePreproc_rule target)
    set(inputVar "-mcpu=24HJ128GP504;-g;-DXPRJ_MPLAB=MPLAB;-Wa,--defsym=__MPLAB_BUILD=1,--no-relax,;-mdfp=/home/xDNA/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_DRIVERS_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_CONTROL_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_HARD;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_SOFT;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_MAIN;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_INTERRUPTIONS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_STREAMS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_TASK;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Include;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/PIC24;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/MemMang")
endfunction()
function(GameCat_R3_MPLAB_compile_rule target)
    set(inputVar "-mcpu=24HJ128GP504;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};${COMPILER_STACK};-g;-DXPRJ_MPLAB=MPLAB;-mlarge-code;-mlarge-data;-mlarge-scalar;-O0;-msmart-io=1;-Wall;-msfr-warn=off;${INLINE_OVERRIDE};-mdfp=/home/xDNA/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_DRIVERS_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_CONTROL_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_HARD;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_SOFT;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_MAIN;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_INTERRUPTIONS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_STREAMS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_TASK;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Include;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/PIC24;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/MemMang")
endfunction()
function(GameCat_R3_MPLAB_link_rule target)
    set(inputVar "-mcpu=24HJ128GP504;${INSTRUMENTED_TRACE_OPTIONS};${PC_SAMPLING_PROFILING_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-g;-DXPRJ_MPLAB=MPLAB;-Wl,--script=p24HJ128GP504.gld,--local-stack,${PRESERVE_FILE},--defsym=__MPLAB_BUILD=1,${MP_LINKER_FILE_OPTION},--heap=128,,--stack=16,,--check-sections,,--data-init,,--pack-data,,--handles,,--isr,,--gc-sections,,--fill-upper=0,,--stackguard=16,,--no-force-link,,--smart-io,,--report-mem,,--memorysummary,memoryfile.xml;-mdfp=/home/xDNA/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_DRIVERS_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_CONTROL_HAL;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_HARD;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_LIBRARIES_SOFT;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_MAIN;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_INTERRUPTIONS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_STREAMS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_TASK;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Include;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/PIC24;${CMAKE_CURRENT_SOURCE_DIR}/../../../P24H_FreeRTOS/Portable/MemMang")
endfunction()
